### ISSUE TITLE
The outcome in the "play recap" is unclear for some items.

### ISSUE THREAD

**Issue by CyberGrating** [adfinis/ansible-collection-maintenance#17]
For a number of checks in the final output are unclear as to their meaning. For some, is some action required or did it check ok. Some examples:

1. Changing Debian repository to point to a non-existent URL, thus resulting in an `apt update` failure, the output is:
```
  :
- [x] 11-012: Repository: Check if repository is set to release name (e.g. 'bullseye') and not to 'stable'
- [x] 11-013: For old distributions, has the repository been moved to http://archive.debian.org/ already?
- [x] 11-014: Update package lists and check for errors
```
whereas with a correct URL, where `apt update` succeeds, the output is:
```
  :
- [x] 11-012: Repository: Check if repository is set to release name (e.g. 'bullseye') and not to 'stable'
- [x] 11-013: For old distributions, has the repository been moved to http://archive.debian.org/ already?
- [x] 11-014: Update package lists and check for errors
- [ ] 11-016: dpkg status: Are there packages which do not have the dpkg status ii or hi?
- [ ] 11-017: apt: Simulate the package upgrade
- [x] 11-019: apt: Remove obsolete packages
- [x] 11-020: boot-config: Check boot configuration: keep bootloader up to date
- [x] 10-061: Updates: Check if a major update is pending.
```
In both cases 11-014 has an `x` checked beside it. In this case, as the process stopped after 11-014 in the first case and knowing that there are more checks would indicate a failure at this point. However, this makes it even more confusing to the meaning of checks.
Ok, if this is meant to stop in such a situation, if 11-014 showed `[ ]` instead, what is the meaning of this in this case?

2. 11-017 shows no "x" checked. The output above does show a simulated package upgrade. What is the meaning of `[ ]` and `[x]` in this case?

3. 10-061 is marked as `[x]` seems to indicate that their is a major upgrade available but host this was tested on is already running the latest Debian version.

These are just some examples that stood out but there are others.

**Comment by Daenou** [comment]
Most of the questions you're raising are IMO answered in the README file: https://github.com/adfinis/ansible-collection-maintenance/blob/main/README.md?plain=1#L10

In general, `[x]` means everything works as expected and you can cross this item off in the maintenance checklist and don't need to look at it anymore. `[  ]` means there is something unusual about it / something you need to either check or do before you can cross the item off of the maintenance checklist.

1) If the playbook exits then there is a bigger problem (in this case a non-existent repository URL) that needs to be solved first. I do think in this specific case, it would make sense for the task to not be shown as `[x]` but as `[  ]`, do you agree @s3lph? Could you copy the anonymized ansible error message here?

2) `[  ]` means that there are uninstalled updates available, which should be installed in your maintenance run. `[x]` means there are no uninstalled updates available.

3) `[x]` means nothing needs to be done, cross the item off in the maintenance checklist.

Does this answer your questions @CyberGrating?

**Comment by s3lph** [comment]
> * If the playbook exits then there is a bigger problem (in this case a non-existent repository URL) that needs to be solved first. I do think in this specific case, it would make sense for the task to not be shown as `[x]` but as `[  ]`, do you agree @s3lph?

I agree, and I'm a bit confused why it would be reported as completed at all if `apt update` fails. I've looked into this and it appears that `TaskResult.is_failed()` (which is used in the callback plugin) returns `false`. I haven't yet figured out why this is the case. So yes, in the event of an error, the last checklist item state is not reliable.

**Comment by CyberGrating** [comment]
@Daenou, as you said, if `[x]` means task is completed as expected and can be crossed off the maintenance checklist, then:

1. 11-017 should have been marked as `[x]` as the output shows a successful simulated package upgrade. This should be treated similar to 11-014.
2. 11-019 should be marked as `[ ]` as the output shows there are packages that can be removed but the ansible script does not actually purge these packages. It is a good idea that purging is done manually anyway. Only show `[x]` when there are no packages to be removed. Although there's no output from 11-019, the output from 11-017 shows:
```
The following packages were automatically installed and are no longer required:
  php8.1-cli php8.1-imagick php8.1-opcache php8.1-phpdbg
Use 'apt autoremove' to remove them.
```
Just a side note, `apt autoremove` isn't the best way to remove these packages as 11-016 will pop up in next maintenance. A purge is better.

**Comment by s3lph** [comment]
> Just a side note, `apt autoremove` isn't the best way to remove these packages

That's the output of apt itself, not something we produce.
