### ISSUE TITLE
10-039 Check for Storage = persistent causes check to fail

### ISSUE THREAD

**Issue by CyberGrating** [adfinis/ansible-collection-maintenance#5]
Currently, the first check for 10-039 in `roles/maintenance_10_linux/tasks/main.yml` checks to see if the line `Storage=persistent`. When `Storage=auto` (as by default) and the `/var/log/journal` dir exists, "auto" behaves as "persistent" as according to the man pages. Is this the desired effect that we want and if so, could we include the check for this?

**Comment by s3lph** [comment]
Fixed in #19
